### PR TITLE
initial commit for swift3

### PR DESCRIPTION
**Pull request by hollanderbart**
Converted the framework to swift3

### CODE REVIEW

**Comment by kunass2** [comment]
Hi, I cannot merge your pull request to master yet. I do it once after Xcode 8 will be released.

**Comment by hollanderbart** [comment]
Ofcourse, that sounds logically. I will keep the PR up to the latest beta/release version of swift 3.

**Comment by kunass2** [comment]
I really appreciate your help:) good job:) I merge it soon, i think within a 2 months...

**Comment by thomasccpereira** [comment]
Hi, guys! Very nice work!
How about this Swift 3 merge? I just updated my code to newest Swift and I received 53 issues with BSTableViewReorder. :(

**Comment by hollanderbart** [comment]
There still is some work to be done ;)

**Comment by kunass2** [comment]
I know;) That pod is not updated to Swift 3 yet;) need to do it within days;)

---
Bartłomiej Semańczyk

**Comment by kunass2** [comment]
Hi guys, I do not know what is wrong... but I updated `BSTableViewReorder`, (also to cocoapods) to Swift 3, 5 months ago. The latest version is 1.6. Could you tell me more what is exact issue?

**Comment by thomasccpereira** [comment]
Well, I converted my project to Swift 3 and then updated my pod BSTableViewReorder. BSTableViewReorder didnt build, major of errors is differences between Swift 2.3 and Swift 3, like "where" in place of comma. Don't know why It isn't updating. :(

**Comment by kunass2** [comment]
Please, read about "Use legacy Swift language version":)

**Comment by thomasccpereira** [comment]
I'll, thanks.

**Pull request closed without merging**
